### DISCUSSION TITLE
How to change the (blue) color of border and selection in list?

### DISCUSSION THREAD

**Discussion by ddogfoodd** [anyrun-org/anyrun#139] [Q&A]
How can I change the blue border color of the text input field and the blue background of the selection in the list?

**Comment by deepanchal** [comment]
@ddogfoodd 
I found this solution to remove blue border in one of the discussion posts https://github.com/anyrun-org/anyrun/discussions/71#discussioncomment-9752077

```css
* {
  all: unset;
}
```

Here's my wip `style.css`

![image](https://github.com/user-attachments/assets/a366154f-22f3-42a7-92f8-3c20dc249e77)

```css
* {
  all: unset;
}

#window {
  background: transparent;
}

#entry {
  font-size: 1.2rem;
  caret-color: #89b4fa;
  border-radius: 8px 8px 0px 0px;
  padding: 8px 16px;
  background-color: #181825;
}

#entry:focus {
  border: none;
}

list {
  background-color: #181825;
}

list#main {
  border-radius: 0px 0px 8px 8px;
  background-color: #181825;
}
list#main:focus,
list#main:selected {
  border: none;
  background-color: #181825;
}

/* anyrun's ouput matches entries */
list #match {
  color: #cdd6f4;
}

list #match:selected,
list #match:hover {
  background-color: #89b4fa;
}

list #match:selected label,
list #match:hover label {
  color: #181825;
}
```
