### DISCUSSION TITLE
Sharing rices

### DISCUSSION THREAD

**Discussion by deepanchal** [anyrun-org/anyrun#179] [Show and tell]
Just wanted to share my anyrun rice using [`catppuccin-mocha`](https://catppuccin.com/) theme with `blue` accent :)

## Screenshots

![image](https://github.com/user-attachments/assets/a727a8b9-8b01-4fe4-a3bf-dff662ef6060)

## Style

```css
/* GTK Vars */
@define-color bg-color #313244;
@define-color fg-color #cdd6f4;
@define-color primary-color #89b4fa;
@define-color secondary-color #cba6f7;
@define-color border-color @primary-color;
@define-color selected-bg-color @primary-color;
@define-color selected-fg-color @bg-color;

* {
  all: unset;
  font-family: JetBrainsMono Nerd Font;
}

#window {
  background: transparent;
}

box#main {
  border-radius: 16px;
  background-color: alpha(@bg-color, 0.6);
  border: 0.5px solid alpha(@fg-color, 0.25);
}

entry#entry {
  font-size: 1.25rem;
  background: transparent;
  box-shadow: none;
  border: none;
  border-radius: 16px;
  padding: 16px 24px;
  min-height: 40px;
  caret-color: @primary-color;
}

list#main {
  background-color: transparent;
}

#plugin {
  background-color: transparent;
  padding-bottom: 4px;
}

#match {
  font-size: 1.1rem;
  padding: 2px 4px;
}

#match:selected,
#match:hover {
  background-color: @selected-bg-color;
  color: @selected-fg-color;
}

#match:selected label#info,
#match:hover label#info {
  color: @selected-fg-color;
}

#match:selected label#match-desc,
#match:hover label#match-desc {
  color: alpha(@selected-fg-color, 0.9);
}

#match label#info {
  color: transparent;
  color: @fg-color;
}

label#match-desc {
  font-size: 1rem;
  color: @fg-color;
}

label#plugin {
  font-size: 16px;
}
```

**Comment by lucasfnCode** [comment]
Congratulations on the styling, it's very beautiful, and thanks for sharing it, it was the only one I found with an example to develop mine.

How did you manage to add blur only in anyrun @deepanchal  ?

I'm in Hyprland and when I add in my configuration:

layerrule = blur, anyrun

the blur is applied to my entire window when calling anyrun, not just in the area it is occupying

**Reply by de-mirage2** [reply]
I'm having the same issue, the blur applies to the entire window. Was a fix ever found for this?

**Reply by de-mirage2** [reply]
Never mind @lucasfnCode , I found the fix from #168 I think.
I just had to use these layer rules:
```
# hyprland.conf
layerrule = blur,anyrun
layerrule = ignorezero,anyrun
```
<img width="1062" height="750" alt="image" src="https://github.com/user-attachments/assets/e5c0b367-f0ef-4db0-a277-8f83d00da94d" />

**Comment by ryan4yin** [comment]
Thanks for sharing! I ported your CSS to GTK4 so it works properly with the latest version of Anyrun. Here’s my modified version:

## Screenshots
<img width="1202" height="1048" alt="image" src="https://github.com/user-attachments/assets/18d11df7-2654-487f-b16f-4eeefb338b0b" />

## Style

```css
/* ===== Color variables ===== */
:root {
  --bg-color: #313244;
  --fg-color: #cdd6f4;
  --primary-color: #89b4fa;
  --secondary-color: #cba6f7;
  --border-color: var(--primary-color);
  --selected-bg-color: var(--primary-color);
  --selected-fg-color: var(--bg-color);
}

/* ===== Global reset ===== */
* {
  all: unset;
  font-family: "JetBrainsMono Nerd Font", monospace;
}

/* ===== Transparent window ===== */
window {
  background: transparent;
}

/* ===== Main container ===== */
box.main {
  border-radius: 16px;
  background-color: color-mix(in srgb, var(--bg-color) 80%, transparent);
  border: 0.5px solid color-mix(in srgb, var(--fg-color) 25%, transparent);
  padding: 12px; /* add uniform padding around the whole box */
}

/* ===== Input field ===== */
text {
  font-size: 1.3rem;
  background: transparent;
  border: 1px solid var(--border-color);
  border-radius: 16px;
  margin-bottom: 12px;
  padding: 5px 10px;
  min-height: 44px;
  caret-color: var(--primary-color);
}

/* ===== List container ===== */
.matches {
  background-color: transparent;
}

/* ===== Single match row ===== */
.match {
  font-size: 1.1rem;
  padding: 4px 10px; /* tight vertical spacing */
  border-radius: 6px;
}

/* Remove default label margins */
.match * {
  margin: 0;
  padding: 0;
  line-height: 1;
}

/* Selected / hover state */
.match:selected,
.match:hover {
  background-color: var(--selected-bg-color);
  color: var(--selected-fg-color);
}

.match:selected label.plugin.info,
.match:hover label.plugin.info {
  color: var(--selected-fg-color);
}

.match:selected label.match.description,
.match:hover label.match.description {
  color: color-mix(in srgb, var(--selected-fg-color) 90%, transparent);
}

/* ===== Plugin info label ===== */
label.plugin.info {
  color: var(--fg-color);
  font-size: 1rem;
  min-width: 160px;
  text-align: left;
}

/* ===== Description label ===== */
label.match.description {
  font-size: 0rem;
  color: var(--fg-color);
}

/* ===== Fade-in animation ===== */
@keyframes fade {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
```
