### ISSUE TITLE
CSS selector for active element

### ISSUE THREAD

**Issue by Shaharyar-developer** [anyrun-org/anyrun#151]
I am unable to figure out which css selector selects the current active list element instead of every list element.
I have tried element:foucs, element:hover and element:hover.

**Comment by Lau-San** [comment]
You can select the active element with `#match:selected`.

```css
#match:selected {
    background-color: red;
}
```

![20240628_22h40m47s_grim](https://github.com/anyrun-org/anyrun/assets/25137618/7632e21b-32f2-4491-9cdf-b4135c6132ea)
