### ISSUE TITLE
do not display empty list element (on launch)

### ISSUE THREAD

**Issue by fybx** [anyrun-org/anyrun#178]
First of all, thanks for the project!

I am trying to get anyrun to look more like [Spotlight](https://en.wikipedia.org/wiki/Spotlight_(Apple)) and I couldn't get the "list" element that contains the rows (of plugins) to hide when there's nothing to be shown.

Here's what it looks like:
![image](https://github.com/user-attachments/assets/bc6196fd-9264-4275-8922-11e940e9b3d5)

And here are the nodes, I am certain that my issue is with element `list` with ID `main`
![image](https://github.com/user-attachments/assets/c13305e9-1882-4973-b7eb-fb58c53f0271)

---

Here's the CSS I am using right now:

```css
window {
    background-color: transparent;
}

entry {
    border: none;
    box-shadow: 0 8px 16px -8px #555;
    border-radius: 8px;
    font-size: 16px;
    padding: 8px 16px;

    margin-bottom: 16px;
}

main {
    border: none;
    border-radius: 8px;
    font-size: 16px;
    padding: 8px 16px;
}

list {
    border: none;
    border-radius: 8px;
    font-size: 16px;
}
```

**Comment by deepanchal** [comment]
Have you tried doing a style reset before applying your styles?

```css
* {
  all: unset;
}

/* other styles */
```

I found this solution in one of discussion posts https://github.com/anyrun-org/anyrun/discussions/71#discussioncomment-9752077
